service: moderngodaam
provider:
  name: aws
  runtime: python3.6
  region: ap-south-1
  stage: dev

plugins:
  - serverless-python-requirements
  - serverless-offline-python

package:
  exclude:
    - Pipfile
    - Pipfile.lock
    - package-lock.json
    - node_modules/**

functions:
  send-email:
    handler: handler.email
    events:
      - http:
          path: v1/email
          method: post
          cors: true
